### ISSUE TITLE
Logs are not in order if `@timestamp` is the same

### ISSUE THREAD

**Issue by BenJeau** [vklochan/python-logstash#102]
Hi, thanks for this library, so I have some consecutive logs that have the same `@timestamp` but looking in Kibana, they are not in the order that they are printed in the code

For example, the first and last logs are in the right order here, but the two in the middle are not:
![image](https://user-images.githubusercontent.com/22248828/172252635-5ab834cd-a02f-4be8-bb43-1f83c5fb8a1a.png)

Has this happened to anyone else and is there a possible fix for this?

**Comment by rhoitjadhav** [comment]
I think its because of the same timestamp and it is not able to decide which one to put 1st and 2nd.
