### ISSUE TITLE
[Question] Django to Elasticsearch not using logstash?

### ISSUE THREAD

**Issue by scheung38** [vklochan/python-logstash#105]
Hi I posted in elastic.co but maybe here is more appropriate since this is logstash related

https://discuss.elastic.co/t/django-syncs-to-elasticsearch-even-when-logstash-container-is-removed/313878

**Comment by RomkaSk** [comment]
Could you provide your Django configuration for logging? I can't reproduce your case.

Example of the correct logging configuration for django:
_settings.py_
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'logstash': {
            'level': 'DEBUG',  
            'class': 'logstash.LogstashHandler',
            'host': '127.0.0.1',  
            'port': 5959,    
            'version': 1,
            'message_type': 'django',  
        },
    },
    'loggers': {
        'django': {
            'handlers': ['logstash'],
            'level': 'DEBUG', 
            'propagate': False,
        },
    },
}

```

**Comment by vklochan** [comment]
I close the topic, as an example of the correct config was provided.
