### ISSUE TITLE
Clarification Required: BaseLogstash Handler i.e (LogstashHandler) is equivalent to the UDPLogstashHander?

### ISSUE THREAD

**Issue by srizzling** [vklochan/python-logstash#14]
This more me being a noob, but I am guessing that BaseLogstash Handler is the same as the UDP Handler defined? (I'm new to python :P)

https://github.com/vklochan/python-logstash/blob/master/logstash/handler_udp.py#L21

Sorry for any inconvenience :P

**Comment by vklochan** [comment]
You're right. LogstashHandler is for backward compatibility with the older versions of the library.
