### ISSUE TITLE
Example Logstash config

### ISSUE THREAD

**Issue by asmaps** [vklochan/python-logstash#15]
An example Logstash config would be helpful to get started easier.

I will post my own as soon as I have a working one - but maybe the author also could post his/add it to the README? :-)

**Comment by alex--m** [comment]
+8! (needs to be somewhere in the repo...)

**Comment by reiven** [comment]
ping @vklochan

**Comment by muriloacs** [comment]
up

**Comment by shreyu86** [comment]
I have opened #36 to add the logstash config as a note in the readme.

**Comment by vklochan** [comment]
Done in #36. Closing the issue.
