### ISSUE TITLE
why ? python-logstash ' json have not grok effect ...

### ISSUE THREAD

**Issue by rfyiamcool** [vklochan/python-logstash#29]
I thank message'field is field,not json string 

from kibana

@timestamp	  	2015-03-30T05:09:42.151Z
@version	  	1
_id	  	AUxpFdtj8ZYGI1FQ4LPB
_index	  	logstash-2015.03
_type	  	logs
host	  	192.168.1.50
message	  	{"nima": "ruifengyun", "message": {"@source": "logstash://bj-log-1/run.py", "source": "ruifengyun", "@source_host": "bj-log-1", "@message": "python-logstash: test extra fields", "@tags": [], "@fields": {"test_integer": 123, "nima": "ruifengyun", "test_dict": {"a": 1, "b": "c"}, "test_boolean": true, "test_list": [1, 2, "3"], "test_float": 1.23, "logger": "python-logstash-logger", "levelname": "INFO", "test_string": "ruifengyun(2, 6, 6, 'final', 0)"}, "@timestamp": "2015-03-30T05:09:42.150821Z", "@source_path": "run.py", "@type": "logstash"}}

**Comment by vklochan** [comment]
Please provide your code/configuration to identify the issue.

**Comment by vklochan** [comment]
I'm closing the issue due to the open questions.

**Comment by fujiawei-dev** [comment]
I want to know why too.
