### ISSUE TITLE
Examples in the readme do not match up

### ISSUE THREAD

**Issue by X-Trade** [vklochan/python-logstash#38]
I was running through how to set this up, most specifically the receiving part in logstash. 

I noticed in your examples you set the handler's target host port to 5959, but in the example logstash configuration it is port 5000. 

Additionally, it's mentioned we're sending messages to logstash using UDP, but the logstash configuration example is for a TCP input.

**Comment by X-Trade** [comment]
Is there some proper documentation aside from the readme?

**Comment by virajh** [comment]
Trying to run the example I see  the following exception:
Traceback (most recent call last):
  File "logstash_python.py", line 9, in <module>
    test_logger.addHandler(logstash.LogstashHandler(host, port, version=1))
AttributeError: 'module' object has no attribute 'LogstashHandler'

**Comment by humbled** [comment]
@X-Trade UDP was built first, but you can use either. TCP is best for robustness.
You're right that 5000 would be more consistent with the config recommendations, use that in your setup.
Apart from the readme, other's previous questions in these issues was helpful for me getting started.

**Comment by vklochan** [comment]
@X-Trade, readme is updated here: https://github.com/vklochan/python-logstash/pull/43. The request is merged.

**Comment by vklochan** [comment]
@virajh, please make sure that your virtual environment is activated. See example: https://github.com/vklochan/python-logstash.
