### ISSUE TITLE
Tip: Global exception handling

### ISSUE THREAD

**Issue by humbled** [vklochan/python-logstash#49]
Just had to work this out for myself. If you're dependent on logstash for keeping records, then unhandled exceptions should really be shipped there too. I did this by calling the method below in my setup:

```
def config_global_exception_handling():
    '''
    Override the global exception hook to come here.
    Here, log the exception which includes sending to logstash.
    '''
    def customexcepthook(exc_type, exc_value, exc_traceback):
        sys.exc_info = lambda: (exc_type, exc_value, exc_traceback)
        logging.exception('Unhandled exception')
    sys.excepthook = customexcepthook
```

"Unhandled exception" becomes the _message_ attribute, and the _stack_trace_ attribute gets populated appropriately

**Comment by vklochan** [comment]
Thanks for your feedback.
