### ISSUE TITLE
Throwing TypeError when logging

### ISSUE THREAD

**Issue by erip** [vklochan/python-logstash#53]
I have a StackOverflow [question](http://stackoverflow.com/questions/38032782/why-is-my-logstash-handler-throwing-a-typeerror), but it hasn't gotten any attention, so I thought I'd bring it up here.

___

# The requirement:

Create a logger that can log the `hostname` as a part of the formatter. The logger will have many handlers, one of which is a logstash handler.

# The code:

```
import logging
import logstash

from socket import gethostname

class CustomLogger(logging.Logger):
    def _log(self, level, msg, args, exc_info=None, extra=None):
        if extra is None:
            extra = { 'hostname' : gethostname() }
        super(CustomLogger, self)._log(level, msg, args, exc_info, extra)

def setup_custom_logger(host, port):
    # add hostname to the formatter.
    logging.setLoggerClass(CustomLogger)

    formatter = logging.Formatter(fmt='%(hostname)s - %(asctime)s - %(levelname)s - %(module)s - %(message)s')

    logstash_handler = logstash.LogstashHandler(host, port, version=2)
    logstash_handler.setLevel(logging.DEBUG)
    logstash_handler.setFormatter(formatter)

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    logger.addHandler(logstash_handler)

    return logger
```

# The issue:

Logging anything results in:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/handlers.py", line 620, in emit
    self.send(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/handlers.py", line 678, in send
    self.sock.sendto(s, self.address)
TypeError: a bytes-like object is required, not 'str'
```

I've tried `logger.info('hello')`, `logger.info(b'hello')`, `logger.info(1)` -- they always result in a TypeError.

Does anyone have an idea why this isn't working? I'm using 0.4.6.

**Comment by erip** [comment]
The problem seemed to be with the formatter. I removed that line and it successfully logged to logstash according to the config.

**Comment by gksoriginals** [comment]
@erip how is that a solution ? I need to add a formatter to the Logstash log.
