### ISSUE TITLE
Import Event error 

### ISSUE THREAD

**Issue by sangmeshcp** [vklochan/python-logstash#62]
../../lib/logger/elkhandler.py:5: in <module>
    import logstash
lib/python3.4/site-packages/logstash/__init__.py:2: in <module>
    from event import Event
E   ImportError: No module named 'event'

I have installed events and python-logstash using pip and both are satisfied.. I'm using python 
 python --version 
Python 3.4.3

 pip install events 
Requirement already satisfied: events in /lib/python3.4/site-packages
 pip install python-logstash 
Requirement already satisfied: python-logstash in /lib/python3.4/site-packages

**Comment by sangmeshcp** [comment]
actually found the issue .. i had pip install logstash which was being called instead of python-logstash ... removed the logstash using pip uninstall logstash solved the problem...

**Comment by RutujaWanjari** [comment]
Hello there,

I have installed python-lostash, still I am getting "ModuleNotFound: No module named event" on -
`from event import Event`

Python Environment -- Python 3.6.4 :: Anaconda custom (64-bit)

**Comment by BRIGHTON-ASUMANI** [comment]
Have you tried using events instead of event
