### ISSUE TITLE
ResourceWarning: unclosed <socket ...>

### ISSUE THREAD

**Issue by exhuma** [vklochan/python-logstash#68]
When using the `TCPLogstashHandler` and sending a message, I get the following warning:

    ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('172.27.0.74', 36854), raddr=('172.27.0.63', 5001)>

I'm not certain if this comes from the underlying `SocketHandler` from Python or from `python-logstash`. If it's the former, feel free to close this issue.

**Comment by vklochan** [comment]
Thanks for your feedback. This doesn't apply to the module. I close the issue.
