### ISSUE TITLE
How to limit the number of UDP sockets opened ?

### ISSUE THREAD

**Issue by shreyashah** [vklochan/python-logstash#79]
Because, I am running into I/O Error : too many files opened.
And when I do, lsof| grep pid, I see a lot of UDP connections opened and eventually I exhaust on the ulimit number. As soon as the ulimit number is exhausted, and more UDP sockets need to be opened for logging to log stash, I/O Error : too many files opened is encountered.

Raising ulimit doesn't completely fix this. Please help.

**Comment by RomkaSk** [comment]
Perhaps you have already solved this problem, but here are a few solutions for it:
- Using TCP instead of UDP 
- Properly closing the logstash handler or logger when it's no longer needed
- Reusing the same handler instead of creating a new

**Comment by vklochan** [comment]
Closing this issue based on the previous comment.
