### ISSUE TITLE
Please document that the project is not using semantic versioning.

### ISSUE THREAD

**Issue by exhuma** [vklochan/python-logstash#80]
Given that this is a utility library, it would make sense to follow semantic versioning.

In fact, the change in `0.4.6` (renaming field names) changed the external API. We mistakenly believed that `python-logstash` would follow semantic versioning and pinned our dependencies using `python-logstash >= 0.4.2, <1.0` so the `0.4.6` update was included in our updates.

This has now created a *bunch* of entries in our ELK stack with the wrong field names and our visualisations now show *incorrect* information. And this was only noticed by pure chance.

It would be nice if the versioning scheme used in `python-logstash` would be documented so nobody else falsely assumes that this is semver.

**Comment by wizardion** [comment]
Valid comment. It will be reviewed on the next update. Thanks. 

For now, I close this issue.

**Comment by exhuma** [comment]
Awesome. Thank you.
