### ISSUE TITLE
AttributeError: module 'logstash' has no attribute 'LogstashHandler'

### ISSUE THREAD

**Issue by yuseferi** [vklochan/python-logstash#81]
my Logstash is up and running in my system but when I wanted to test you sample code faced with 

AttributeError: module 'logstash' has no attribute 'LogstashHandler'

while I've installed  logstash package in my system.

python version : 3.6

**Comment by aeciovc** [comment]
Are you trying extends the LogstashHandler or something like this? LogstashHandler is just a variable to address to UDPLogstashHandler for default.

**Comment by nav1n** [comment]
I had this same issue, you might be using the old logstash package, you can try:
pip uninstall logstash
pip install python-logstash

**Comment by wizardion** [comment]
Looks like the issue was resolved. 
In case of any problems, please reopen this issue.

**Comment by JJ** [comment]
I had exactly the same problem running the example on the main Pypi page. python-logstash version is 0.4.6, the mentioned logstash is not installed. I have tested it with two Python versions. 3.9 and 3.8.6

**Comment by timreibe** [comment]
@JJ had the same issue after accidentally installing the old package. Uninstalling both and reinstalling the new one solved my issue

```bash
pip uninstall logstash
pip uninstall python-logstash

pip install python-logstash
```

**Comment by manishsparxIt2** [comment]
it is not working for me
