### ISSUE TITLE
Broken example on list with elements of different types

### ISSUE THREAD

**Issue by roman-telepathy-ai** [vklochan/python-logstash#83]
hi
in the example in the README
```
extra = {
    'test_string': 'python version: ' + repr(sys.version_info),
    'test_boolean': True,
    'test_dict': {'a': 1, 'b': 'c'},
    'test_float': 1.23,
    'test_integer': 123,
    'test_list': [1, 2, '3'],
}
```

you mention a list `'test_list': [1, 2, '3'],`, where elements have different types ==> THIS IS NOT WORKING!

**Comment by nurettin** [comment]
That example doesn't work, because elasticsearch expects [Long] but receives [Text] and a corrupted index will be created. Further messages are not added to documents for that index.

**Comment by madkote** [comment]
@nurettin thx for reply, maybe it is better to adjust example in the README. Then it would be clear.

Thx

**Comment by wizardion** [comment]
Each field in the `extra` dictionary, is reported as a JSON string. In the Logstash, the test_list should look like this: ![2020-02-25_14-40](https://user-images.githubusercontent.com/2981194/75281272-fa2e9580-57dc-11ea-9688-87a156bb489f.png)

Please send any details if you still need some help.
