### ISSUE TITLE
Log entries with nested dicts get silently ignored

### ISSUE THREAD

**Issue by denizdogan** [vklochan/python-logstash#84]
I am using this logger for a Django project and it seems that whenever I try to log a nested JSON object, it gets silently ignored. The following works fine:

    logger.debug('trace', extra={
        # 'request': {
        #     'path': request.get_full_path()
        # },
        'path': request.get_full_path(),
    })

But this one gets silently ignored:

    logger.debug('trace', extra={
        'request': {
            'path': request.get_full_path()
        },
        'path': request.get_full_path(),
    })

Any ideas?

**Comment by wizardion** [comment]
Logstash doesn't have nested fields, that's why it is ignored. If you need to track nested entries, put it as a dictionary into one certain field. It will be reported as a JSON string in the logs.
