### ISSUE TITLE
Should stack_info be added to skip list?

### ISSUE THREAD

**Issue by AlanCoding** [vklochan/python-logstash#85]
Here are two other similar libraries, and they both maintain a similar list of blacklisted keys which would conflict with the python log record stuff:

https://github.com/marselester/json-log-formatter/blob/master/json_log_formatter/__init__.py

https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py

The one notable field that _those_ have which _this_ library doesn't have is `stack_info`, so I wanted to ask whether this is something that should be added.

It seems this was added to the log record in some python version

https://github.com/python/cpython/blob/b7d62050e7d5fc208ae7673613da4f1f2bc565c4/Lib/logging/__init__.py#L336

Its appearance there seems to be comparable to the other fields

**Comment by wizardion** [comment]
Added a new commit about this issue, the changes will be after the merging is completed. 

For now, I close this issue.
