### ISSUE TITLE
How can we add authentication to logstash?

### ISSUE THREAD

**Issue by singhravi1** [vklochan/python-logstash#87]

**Comment by CameronNemo** [comment]
Use SSL with your own certificate authority.

**Comment by singhravi1** [comment]
I was thinking about authenticating so that no one else can just send the data to my logstash server. Can they?

**Comment by wizardion** [comment]
What kind of authentication would you like to have?
It is just a python handler to push messages to the logstash itself. 
Does the logstash support user authentication?  As the previous comment says, you can use an SSL certificate. I'm closing this issue, but if you have any question please reopen it.

**Comment by singhravi1** [comment]
@wizardion 
There is an user based authentication option in the [node version](https://github.com/fluent/fluent-logger-node) of this library.
I was expecting the same kind in this library also.
