### ISSUE TITLE
Formatting of extra fields, repr() vs str()

### ISSUE THREAD

**Issue by adaitche** [vklochan/python-logstash#91]
https://github.com/vklochan/python-logstash/blob/a8be251ad9fc102af668c38a5397515b0804da75/logstash/formatter.py#L45

The value of extra fields are formatted via `repr()`. In most cases it seems to me that `str()` would be better. A typical example is `Path` objects:

```python
from pathlib import Path
path = Path("foo/bar")
print(repr(path))
print(str(path))
```

The repr-version is `PosixPath('foo/bar')`, whereas the str-version is `foo/bar`. In logs, I always want to have the latter version and, currently, have to manually enforce this via `extra={"path": str(path)}`. This is also true for many other objects.

According to Python [docs](https://docs.python.org/3/reference/datamodel.html#object.__repr__) `repr()` should return "the “official” string representation of an object" whereas `str()` should return a "nicely printable string representation of an object". For logs, I think, the latter is almost always what one wants. 

Therefore my question: would you be open to changing the formatting of extra fields from `repr()` to `str()`? Am I missing some reason why it is a bad idea? If you agree, I would submit a PR.

**Comment by vklochan** [comment]
We think that repr  is more informative and valuable in the context of logs. Thanks!
