### ISSUE TITLE
1000ms latency caused by unused config

### ISSUE THREAD

**Issue by alex-treebeard** [vklochan/python-logstash#94]
Hey there, we had some old config sitting around pointing to a localhost logstash – which did not exist.

It turns out that this was causing 1000ms latency when calling `logger.info` for the first time.

I don't understand the root cause, but I just thought I would note here that this seems like a silent failure mode which could be fixed.

Related django config

```
            "logstash": {
                "level": "INFO",
                "class": "logstash.TCPLogstashHandler",
                "host": os.getenv("LOGS_IP", "localhost"),
                "port": 5000,  # Default value: 5000
                "version": 1,
                "message_type": "django_logstash",  # 'type' field in logstash message.
                "fqdn": False,  # Fully qualified domain name. Default value: false.
                # 'tags': ['django.request'],  # list of tags. Default: None.
            },
```

**Comment by vklochan** [comment]
Can't repeat the issue with UDP or TCP. It might be related to the specific project. Closing the issue.
